### ISSUE TITLE
Setting bitbake.setupScriptPath causes scanning failure

### ISSUE THREAD

**Issue by drewmoseley** [microhobby/vscode-bitbake#2]
If I add the following to settings.json:
```
    "bitbake.setupScriptPath": "${workspaceFolder}/oe-init-build-env"
```
then the bitbake status reports 0 for all components.

**Comment by microhobby** [comment]
Hey @drewmoseley the default script should be set on the `bitbake.oeInitBuildEnvPath` setting.

The `bitbake.setupScriptPath` has some particularities, that are not documented yet. For example, I can write the following script:

```bash
#!/bin/bash

cd /workdir/torizon

# check if the distro is set otherwise exit
if [ -z "$DISTRO" ]
then
    echo "Please set DISTRO env variable"
    exit 69
fi

# check if the machine is set otherwise exit
if [ -z "$MACHINE" ]
then
    echo "Please set MACHINE env variable"
    exit 69
fi

# check if the image is set otherwise exit
if [ -z "$IMAGE" ]
then
    echo "Please set IMAGE env variable"
    exit 69
fi

# check if the build dir is set otherwise exit
if [ -z "$BBDIR" ]
then
    echo "Please set BBDIR env variable"
    exit 69
fi

source setup-environment $BBDIR
"$@"
```

This is useful for distros that have some customized setup environment and the user needs to pass arguments and set environment variables.

**Comment by microhobby** [comment]
Another thing that is good to note, the `bitbake.setupScriptPath` has precedence over the `bitbake.oeInitBuildEnvPath` if the two are set.
