### ISSUE TITLE
Bug: syntax coloration issue when there is `[]`

### ISSUE THREAD

**Issue by FederAndInk** [microhobby/vscode-bitbake#4]
when there is `[]` the coloration stops working after the next `[...]`, it just don't like empty brackets but if there is brackets with something in it it is working again (even just a space like so `[ ]`) see:

![image](https://github.com/microhobby/vscode-bitbake/assets/24270152/f4dd8fef-aecf-4756-87d3-6a0ee3066328)

**Comment by FederAndInk** [comment]
looks like it's been introduced in https://github.com/microhobby/vscode-bitbake/commit/6102018da4cc5b891b7cf9b9523d891214a022d4

**Comment by microhobby** [comment]
@FederAndInk should be working on v2.0.23, already published on Marketplace. Let me know if this does not work for you.

**Comment by FederAndInk** [comment]
Thanks, looks like it's working now :grinning:
