### ISSUE TITLE
 The 'Yocto BitBake' extension is not available in Visual Studio Code for Windows 64 bit.

### ISSUE THREAD

**Issue by SurfCityMojo** [microhobby/vscode-bitbake#5]
Please add 64-bit version to extension.  Thank you!

**Comment by microhobby** [comment]
Hey @SurfCityMojo could you please describe your use case? Let me tell you why I'm publishing for Linux x86_64 only. The commands used to scan files and features require `bitbake` and this necessarily requires a configured Linux environment. Also the extension is being tested only in this Linux x86_64 environment.

**Comment by skycaptain** [comment]
Encountering a similar message, but for Mac Silicon. The scenario is that the original extension `eugenwiens.bitbake` is now considered deprecated and suggests using this new extension instead. While additional features, as you described, are useful and convenient, in my case, I only require syntax highlighting and IntelliSense support, as I build my device images within a container. Similarly, I am aware that many companies utilize VSCode on Windows and employ containers for building. Therefore, it would be great to have some features that are not dependent on running bitbake on other platforms as well.

**Comment by Forside** [comment]
Supporting everything @skycaptain said, we use Bitbake in the WSL and edit recipes via VSCode in Windows. The `eugenwiens.bitbake` extension was crucial for syntax highlighting. I am now seeing the same message about the deprecation of the original extension, leading me to replace it with the new `microhobby.bitbake2`. However as mentioned it can't be installed on Windows. Syntax highlighting alone would be enough for me, but maybe even full WSL support could be integrated? VSCode has native support for WSL and many build environments work fine with it today.

**Comment by microhobby** [comment]
@skycaptain got it, make sense.
@Forside if you have WSL 2 you can use it, is possible to install the extension if you run the `code` command from a WSL 2 terminal, which will make the automatically remote connection to the WSL 2, and then install it.

I will release a new universal version with the bitbake dependent features disabled.

**Comment by SurfCityMojo** [comment]
@microhobby, my use-case is very similar to @skycaptain and @Forside (thanks to them for jumping in on this). I also use the extension under Windows for syntax highlighting and IntelliSense features while editing recipes.

**Comment by microhobby** [comment]
@SurfCityMojo the `v2.0.24` is already released as Universal package on the VS Market Place. Let me know if this works for you.

**Comment by skycaptain** [comment]
Thanks! Seems to work now.

**Comment by skycaptain** [comment]
Just one comment on your change: Consider removing the check for CPU architecture, since architectures such as ARM are gaining popularity rapidly and not just limited to x64.

**Comment by Forside** [comment]
@microhobby Thanks for the update, works perfectly! Highlighting even improved here and there. I will try running the extension in the WSL VS Code, didn't think of that.
